version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "neworder"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1l0u2zm8h6jk5"
s3_prefix = "neworder"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
